"use client";

import Image from "next/image";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type Identity = { first_name: string | null; last_name: string | null; username: string | null; phone: string | null; bio: string | null; avatar_url: string | null; locale: string; city: string | null; neighborhood: string | null };
type Payment = { id: string; amount: number; currency: string; payment_method: string; payment_status: string; provider_reference: string | null; created_at: string; bookings: { provider_services: { title: string } | null } | null };
type Review = { id: string; rating: number; comment: string | null; provider_reply: string | null; is_visible: boolean; created_at: string };
type Ticket = { id: string; subject: string; status: string; created_at: string };
type Counts = { follows: number; saves: number; bookings: number };

const paymentLabels: Record<string,string> = { pending:"À payer", simulated_paid:"Confirmé (test)", paid_on_site:"Confirmé sur place", paid:"Confirmé", failed:"Échoué", refunded:"Remboursé", cancelled:"Annulé" };

export function ClientControlCenter({ userId }: { userId: string }) {
  const [identity,setIdentity]=useState<Identity|null>(null);
  const [counts,setCounts]=useState<Counts>({follows:0,saves:0,bookings:0});
  const [payments,setPayments]=useState<Payment[]>([]);
  const [reviews,setReviews]=useState<Review[]>([]);
  const [tickets,setTickets]=useState<Ticket[]>([]);
  const [privacy,setPrivacy]=useState({profile_visibility:"limited",show_collections:false,show_follows:false,allow_personalized_recommendations:true,allow_marketing_email:false,allow_promotional_notifications:false});
  const [preferences,setPreferences]=useState({favorite_categories:[] as string[],preferred_styles:[] as string[],budget_min:"",budget_max:"",radius_km:15,location_mode:"both",personalization_enabled:true});
  const [notice,setNotice]=useState("");

  const load=useCallback(async()=>{
    const supabase=getSupabaseBrowserClient(); if(!supabase)return;
    await supabase.rpc("initialize_client_control_center");
    const [profile,client,followCount,saveCount,bookingCount,paymentRows,reviewRows,ticketRows,privacyRow,preferenceRow]=await Promise.all([
      supabase.from("profiles").select("first_name,last_name,username,phone,bio,avatar_url,locale").eq("id",userId).single(),
      supabase.from("client_profiles").select("city,neighborhood").eq("profile_id",userId).single(),
      supabase.from("follows").select("follower_id",{count:"exact",head:true}).eq("follower_id",userId),
      supabase.from("post_saves").select("post_id",{count:"exact",head:true}).eq("profile_id",userId),
      supabase.from("bookings").select("id",{count:"exact",head:true}).eq("client_id",userId),
      supabase.from("payments").select("id,amount,currency,payment_method,payment_status,provider_reference,created_at,bookings!inner(client_id,provider_services(title))").eq("bookings.client_id",userId).order("created_at",{ascending:false}).limit(20),
      supabase.from("reviews").select("id,rating,comment,provider_reply,is_visible,created_at").eq("client_id",userId).order("created_at",{ascending:false}),
      supabase.from("support_tickets").select("id,subject,status,created_at").eq("requester_id",userId).order("created_at",{ascending:false}).limit(10),
      supabase.from("profile_privacy_settings").select("*").eq("profile_id",userId).single(),
      supabase.from("profile_preferences").select("*").eq("profile_id",userId).single(),
    ]);
    if(profile.data&&client.data)setIdentity({...profile.data,...client.data} as Identity);
    setCounts({follows:followCount.count??0,saves:saveCount.count??0,bookings:bookingCount.count??0});
    setPayments((paymentRows.data??[]) as unknown as Payment[]); setReviews((reviewRows.data??[]) as Review[]); setTickets((ticketRows.data??[]) as Ticket[]);
    if(privacyRow.data&&!Array.isArray(privacyRow.data))setPrivacy(privacyRow.data); if(preferenceRow.data&&!Array.isArray(preferenceRow.data))setPreferences({...preferenceRow.data,favorite_categories:preferenceRow.data.favorite_categories??[],preferred_styles:preferenceRow.data.preferred_styles??[],budget_min:preferenceRow.data.budget_min?.toString()??"",budget_max:preferenceRow.data.budget_max?.toString()??""});
  },[userId]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);

  const initials=useMemo(()=>`${identity?.first_name?.[0]??"M"}${identity?.last_name?.[0]??"B"}`,[identity]);
  async function saveIdentity(event:FormEvent<HTMLFormElement>){event.preventDefault();const supabase=getSupabaseBrowserClient();if(!supabase)return;const v=new FormData(event.currentTarget);const {error}=await supabase.rpc("update_client_identity",{target_first_name:String(v.get("firstName")??""),target_last_name:String(v.get("lastName")??""),target_username:String(v.get("username")??""),target_phone:String(v.get("phone")??""),target_bio:String(v.get("bio")??""),target_city:String(v.get("city")??""),target_neighborhood:String(v.get("neighborhood")??""),target_locale:String(v.get("locale")??"fr-SN")});setNotice(error?.message??"Profil mis à jour.");if(!error)await load();}
  async function uploadAvatar(file:File){const supabase=getSupabaseBrowserClient();if(!supabase||!file.size)return;if(file.size>5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type)){setNotice("Photo JPG, PNG ou WebP de 5 Mo maximum.");return;}const ext=file.type.split('/')[1];const path=`${userId}/avatar-${crypto.randomUUID()}.${ext}`;const uploaded=await supabase.storage.from("avatars").upload(path,file,{contentType:file.type});if(uploaded.error){setNotice(uploaded.error.message);return;}const avatar_url=supabase.storage.from("avatars").getPublicUrl(path).data.publicUrl;const {error}=await supabase.from("profiles").update({avatar_url}).eq("id",userId);setNotice(error?.message??"Photo mise à jour.");if(!error)await load();}
  async function savePreferences(event:FormEvent<HTMLFormElement>){event.preventDefault();const supabase=getSupabaseBrowserClient();if(!supabase)return;const v=new FormData(event.currentTarget);const row={profile_id:userId,favorite_categories:String(v.get("categories")??"").split(',').map(x=>x.trim()).filter(Boolean),preferred_styles:String(v.get("styles")??"").split(',').map(x=>x.trim()).filter(Boolean),budget_min:Number(v.get("budgetMin"))||null,budget_max:Number(v.get("budgetMax"))||null,radius_km:Number(v.get("radius"))||15,location_mode:String(v.get("locationMode")),personalization_enabled:v.get("personalization")==="on",updated_at:new Date().toISOString()};const {error}=await supabase.from("profile_preferences").upsert(row);setNotice(error?.message??"Préférences enregistrées.");}
  async function savePrivacy(){const supabase=getSupabaseBrowserClient();if(!supabase)return;const {error}=await supabase.from("profile_privacy_settings").upsert({...privacy,profile_id:userId,updated_at:new Date().toISOString()});setNotice(error?.message??"Confidentialité enregistrée.");}
  async function createTicket(event:FormEvent<HTMLFormElement>){event.preventDefault();const supabase=getSupabaseBrowserClient();if(!supabase)return;const form=event.currentTarget;const v=new FormData(form);const {error}=await supabase.from("support_tickets").insert({requester_id:userId,subject:String(v.get("subject")),category:String(v.get("category"))});setNotice(error?.message??"Demande envoyée au support.");if(!error){form.reset();await load();}}
  async function requestDeletion(){if(!window.confirm("Demander la suppression du compte ? Cette demande sera vérifiée avant toute action irréversible."))return;const reason=window.prompt("Motif facultatif")??"";const supabase=getSupabaseBrowserClient();if(!supabase)return;const {error}=await supabase.rpc("request_account_deletion",{target_reason:reason});setNotice(error?.message??"Demande enregistrée. Aucune donnée n’est supprimée immédiatement.");}
  async function becomeProfessional(){const name=window.prompt("Nom de votre activité professionnelle",`${identity?.first_name??"Mata"} Beauty`);if(!name)return;const supabase=getSupabaseBrowserClient();if(!supabase)return;const {error}=await supabase.rpc("request_provider_onboarding",{target_business_name:name});setNotice(error?.message??"Espace professionnel créé. Rechargez votre compte pour poursuivre l’onboarding.");}

  if(!identity)return <article className="panel"><div className="compact-empty">Chargement de votre profil…</div></article>;
  return <section className="client-control-center" id="client-profile">
    <article className="panel client-profile-hero"><div className="client-avatar">{identity.avatar_url?<Image src={identity.avatar_url} alt="Photo de profil" width={88} height={88} unoptimized />:initials}<label aria-label="Modifier la photo"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>e.target.files?.[0]&&void uploadAvatar(e.target.files[0])}/>＋</label></div><div><small>MON PROFIL</small><h2>{identity.first_name} {identity.last_name}</h2><p>@{identity.username??"nom_utilisateur"} · {[identity.neighborhood,identity.city].filter(Boolean).join(', ')||"Localisation à compléter"}</p><span>{identity.bio||"Ajoutez une courte bio pour personnaliser votre espace."}</span></div><button onClick={()=>document.getElementById("edit-client-profile")?.scrollIntoView({behavior:"smooth"})}>Modifier le profil</button><button onClick={()=>document.getElementById("privacy-settings")?.scrollIntoView({behavior:"smooth"})}>Paramètres</button><div className="client-profile-counts"><b>{counts.follows}<small>Suivis</small></b><b>{counts.saves}<small>Vidéos enregistrées</small></b><b>{counts.bookings}<small>Réservations</small></b></div></article>
    <nav className="profile-shortcuts" aria-label="Raccourcis du profil"><a href="#live-bookings">Mes rendez-vous</a><a href="#client-payments">Mes paiements</a><a href="#inspirations">Mes inspirations</a><a href="#booking-conversation">Mes messages</a><a href="#client-reviews">Mes avis</a><a href="#client-support">Support</a></nav>
    {notice&&<p className="dashboard-feedback" role="status">{notice}</p>}
    <article className="panel" id="edit-client-profile"><div className="panel-heading"><div><h2>Identité</h2><p>Les coordonnées privées ne sont jamais affichées publiquement.</p></div></div><form className="dashboard-form" onSubmit={e=>void saveIdentity(e)}><label>Prénom<input name="firstName" required defaultValue={identity.first_name??""}/></label><label>Nom<input name="lastName" required defaultValue={identity.last_name??""}/></label><label>Nom d’utilisateur<input name="username" required pattern="[A-Za-z0-9_]{3,30}" defaultValue={identity.username??""}/></label><label>Téléphone<input name="phone" type="tel" defaultValue={identity.phone??""}/></label><label>Ville<input name="city" defaultValue={identity.city??""}/></label><label>Quartier<input name="neighborhood" defaultValue={identity.neighborhood??""}/></label><label>Langue<select name="locale" defaultValue={identity.locale}><option value="fr-SN">Français</option><option value="en-SN">English</option></select></label><label className="wide">Bio<textarea name="bio" maxLength={280} defaultValue={identity.bio??""}/></label><button className="primary-button">Enregistrer</button></form></article>
    <article className="panel" id="beauty-preferences"><div className="panel-heading"><div><h2>Préférences beauté</h2><p>Utilisées uniquement pour personnaliser le feed lorsque vous l’autorisez.</p></div></div><form className="dashboard-form" onSubmit={e=>void savePreferences(e)}><label className="wide">Catégories favorites<input name="categories" defaultValue={preferences.favorite_categories.join(', ')}/></label><label className="wide">Styles préférés<input name="styles" defaultValue={preferences.preferred_styles.join(', ')}/></label><label>Budget minimum<input name="budgetMin" type="number" min="0" defaultValue={preferences.budget_min}/></label><label>Budget maximum<input name="budgetMax" type="number" min="0" defaultValue={preferences.budget_max}/></label><label>Rayon (km)<input name="radius" type="number" min="1" max="200" defaultValue={preferences.radius_km}/></label><label>Lieu<select name="locationMode" defaultValue={preferences.location_mode}><option value="both">Salon ou domicile</option><option value="salon">Salon</option><option value="mobile">Domicile</option></select></label><label className="wide legal-consent"><input name="personalization" type="checkbox" defaultChecked={preferences.personalization_enabled}/><span>Activer les recommandations personnalisées</span></label><button className="primary-button">Enregistrer</button></form></article>
    <article className="panel" id="client-payments"><div className="panel-heading"><div><h2>Mes paiements</h2><p>Historique privé lié à vos réservations.</p></div></div>{payments.length?payments.map(p=><div className="control-list-row" key={p.id}><div><strong>{p.bookings?.provider_services?.title??"Prestation beauté"}</strong><small>{new Date(p.created_at).toLocaleDateString('fr-FR')} · {p.payment_method.replaceAll('_',' ')}</small><code>{p.provider_reference??p.id.slice(0,12)}</code></div><b>{p.amount.toLocaleString('fr-FR')} {p.currency}<small>{paymentLabels[p.payment_status]??p.payment_status}</small></b></div>):<div className="compact-empty">Aucun paiement enregistré.</div>}</article>
    <article className="panel" id="client-reviews"><div className="panel-heading"><div><h2>Mes avis</h2><p>Seules les réservations terminées peuvent recevoir le badge Réservation vérifiée.</p></div></div>{reviews.length?reviews.map(r=><div className="control-list-row" key={r.id}><div><strong>{'★'.repeat(r.rating)} · Réservation vérifiée</strong><small>{r.comment??"Sans commentaire"}</small>{r.provider_reply&&<p>Réponse du professionnel : {r.provider_reply}</p>}</div><span>{r.is_visible?"Publié":"Modéré"}</span></div>):<div className="compact-empty">Aucun avis publié.</div>}</article>
    <article className="panel" id="client-support"><div className="panel-heading"><div><h2>Support</h2><p>Une demande privée suivie par l’équipe Mata Beauty.</p></div></div><form className="collection-form" onSubmit={e=>void createTicket(e)}><select name="category"><option value="general">Question générale</option><option value="booking">Réservation</option><option value="payment">Paiement</option></select><input name="subject" required minLength={3} maxLength={160} placeholder="Décrivez brièvement votre demande"/><button>Envoyer</button></form>{tickets.map(t=><div className="control-list-row" key={t.id}><strong>{t.subject}</strong><span>{t.status}</span></div>)}</article>
    <article className="panel" id="privacy-settings"><div className="panel-heading"><div><h2>Confidentialité et compte</h2><p>Vos paiements, réservations, messages et tickets restent toujours privés.</p></div></div><div className="privacy-grid"><label>Visibilité du profil<select value={privacy.profile_visibility} onChange={e=>setPrivacy({...privacy,profile_visibility:e.target.value})}><option value="limited">Limitée</option><option value="public">Publique</option></select></label>{([['show_collections','Afficher mes collections'],['show_follows','Afficher mes abonnements'],['allow_personalized_recommendations','Recommandations personnalisées'],['allow_marketing_email','Emails commerciaux'],['allow_promotional_notifications','Notifications promotionnelles']] as const).map(([key,label])=><label className="legal-consent" key={key}><input type="checkbox" checked={privacy[key]} onChange={e=>setPrivacy({...privacy,[key]:e.target.checked})}/><span>{label}</span></label>)}</div><div className="privacy-actions"><button className="primary-button" onClick={()=>void savePrivacy()}>Enregistrer</button><button onClick={()=>void becomeProfessional()}>Devenir professionnel</button><button className="danger-button" onClick={()=>void requestDeletion()}>Demander la suppression du compte</button></div></article>
  </section>;
}
