"use client";

import Image from "next/image";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { publicErrorMessage } from "@/lib/ui/public-error";

type Space = "pro" | "salon";
type ServiceStatus = "draft" | "published" | "paused" | "sold_out" | "archived" | "hidden";
type CatalogService = { id: string; name: string; categories: { name: string } | null };
type CommercialService = {
  id: string; service_id: string; title: string; description: string | null; duration_minutes: number; price_amount: number; currency: string;
  status: ServiceStatus; cover_url: string | null; pricing_mode: "fixed" | "from" | "variable" | "option_based"; price_from_amount: number | null;
  preparation_minutes: number; location_modes: string[]; home_price_amount: number | null; travel_fee_amount: number; deposit_amount: number;
  cancellation_policy: string | null; client_instructions: string | null; capacity: number; business_id: string | null; archived_at: string | null;
  services: { name: string; categories: { name: string } | null } | null;
};
type ServiceOption = { id: string; provider_service_id: string; name: string; description: string | null; price_amount: number; duration_minutes: number; is_required: boolean; is_active: boolean };
type Promotion = { id: string; provider_service_id: string | null; title: string; description: string | null; discount_type: "percentage" | "fixed"; discount_value: number; promotional_price_amount: number | null; starts_at: string; ends_at: string; max_uses: number | null; used_count: number; new_clients_only: boolean; promo_code: string | null; status: string; is_active: boolean };
type Package = { id: string; title: string; normal_price_amount: number; package_price_amount: number; duration_minutes: number; status: string; starts_at: string | null; ends_at: string | null };
type Business = { id: string; name: string };
type Collaborator = { id: string; display_name: string; internal_role: string; commercial_permissions: string[] };
type OfferSection = "services" | "create-service" | "pricing" | "options" | "promotions" | "packages" | "home-services" | "published-offers" | "service-drafts" | "archived-services" | "service-staff" | "service-availability";

const statusLabels: Record<ServiceStatus, string> = { draft: "Brouillon", published: "Publiée", paused: "En pause", sold_out: "Complet", archived: "Archivée", hidden: "Masquée" };
const commercialPermissions = ["service.read","service.create","service.update","service.publish","service.archive","pricing.update","promotion.create","promotion.update","promotion.publish"];

export function CommercialDashboard({userId,space}:{userId:string;space:Space}){
  const [summary,setSummary]=useState({services:0,promotions:0,bookings:0,revenue:0,top:"Aucune réservation"});
  useEffect(()=>{const supabase=getSupabaseBrowserClient();if(!supabase)return;let active=true;const weekStart=new Date();weekStart.setDate(weekStart.getDate()-7);void Promise.all([
    supabase.from("provider_services").select("id",{count:"exact",head:true}).eq("provider_id",userId).eq("status","published"),
    supabase.from("promotions").select("id",{count:"exact",head:true}).eq("provider_id",userId).eq("status","published").eq("is_active",true).lte("starts_at",new Date().toISOString()).gt("ends_at",new Date().toISOString()),
    supabase.from("bookings").select("total_amount,status,provider_services(title)").eq("provider_id",userId).gte("starts_at",weekStart.toISOString()),
  ]).then(([serviceResult,promotionResult,bookingResult])=>{if(!active)return;const bookings=(bookingResult.data??[]) as unknown as Array<{total_amount:number;status:string;provider_services:{title:string}|null}>;const titles=bookings.reduce<Record<string,number>>((result,item)=>{const title=item.provider_services?.title??"Prestation";result[title]=(result[title]??0)+1;return result;},{});const top=Object.entries(titles).sort((a,b)=>b[1]-a[1])[0]?.[0]??"Aucune réservation";setSummary({services:serviceResult.count??0,promotions:promotionResult.count??0,bookings:bookings.length,revenue:bookings.filter(item=>["confirmed","in_progress","completed"].includes(item.status)).reduce((sum,item)=>sum+item.total_amount,0),top});});return()=>{active=false};},[userId]);
  return <section className="workspace-content commercial-offers"><div className="workspace-intro"><div><span>Activité commerciale</span><h2>Votre tableau de bord</h2><p>Les indicateurs essentiels et les prochaines actions, sans mélanger les écrans de gestion.</p></div><div className="workspace-status"><i/>Données réelles · Supabase</div></div><div className="commercial-actions"><Link href={`/${space}/create-service`}>＋ Créer une prestation</Link><Link href={`/${space}/promotions`}>＋ Créer une promotion</Link><Link href={`/${space}/videos`}>▶ Publier une vidéo</Link></div><div className="workspace-metrics commercial-dashboard-metrics"><article><span>Prestations actives</span><strong>{summary.services}</strong></article><article><span>Promotions en cours</span><strong>{summary.promotions}</strong></article><article><span>Réservations cette semaine</span><strong>{summary.bookings}</strong></article><article><span>Chiffre d’affaires suivi</span><strong>{money(summary.revenue)}</strong></article><article><span>Plus réservée</span><strong>{summary.top}</strong></article></div></section>;
}

export function CommercialOffers({ userId, space, initialSection }: { userId: string; space: Space; initialSection: string }) {
  const section = initialSection as OfferSection;
  const [services, setServices] = useState<CommercialService[]>([]);
  const [catalog, setCatalog] = useState<CatalogService[]>([]);
  const [options, setOptions] = useState<ServiceOption[]>([]);
  const [promotions, setPromotions] = useState<Promotion[]>([]);
  const [packages, setPackages] = useState<Package[]>([]);
  const [business, setBusiness] = useState<Business | null>(null);
  const [collaborators, setCollaborators] = useState<Collaborator[]>([]);
  const [bookingCounts, setBookingCounts] = useState<Record<string, number>>({});
  const [mediaCounts, setMediaCounts] = useState<Record<string, number>>({});
  const [editing, setEditing] = useState<CommercialService | null>(null);
  const [feedback, setFeedback] = useState("");
  const [loading, setLoading] = useState(true);

  const load = useCallback(async () => {
    const supabase = getSupabaseBrowserClient(); if (!supabase) return;
    setLoading(true);
    const businessResult = space === "salon" ? await supabase.from("businesses").select("id,name").eq("owner_id",userId).is("archived_at",null).limit(1).maybeSingle() : { data: null, error: null };
    if (businessResult.error) { setFeedback(publicErrorMessage(businessResult.error,"Le salon est indisponible.")); setLoading(false); return; }
    const nextBusiness = businessResult.data as Business | null; setBusiness(nextBusiness);
    const serviceQuery = supabase.from("provider_services").select("id,service_id,title,description,duration_minutes,price_amount,currency,status,cover_url,pricing_mode,price_from_amount,preparation_minutes,location_modes,home_price_amount,travel_fee_amount,deposit_amount,cancellation_policy,client_instructions,capacity,business_id,archived_at,services(name,categories(name))").eq("provider_id",userId).order("created_at",{ascending:false});
    if (space === "salon" && nextBusiness) serviceQuery.eq("business_id",nextBusiness.id); else if (space === "pro") serviceQuery.is("business_id",null);
    const [serviceResult,catalogResult,optionResult,promotionResult,packageResult,bookingResult,mediaResult,collaboratorResult] = await Promise.all([
      serviceQuery,
      supabase.from("services").select("id,name,categories(name)").eq("is_active",true).order("name"),
      supabase.from("service_options").select("id,provider_service_id,name,description,price_amount,duration_minutes,is_required,is_active").order("sort_order"),
      supabase.from("promotions").select("id,provider_service_id,title,description,discount_type,discount_value,promotional_price_amount,starts_at,ends_at,max_uses,used_count,new_clients_only,promo_code,status,is_active").eq("provider_id",userId).order("created_at",{ascending:false}),
      supabase.from("service_packages").select("id,title,normal_price_amount,package_price_amount,duration_minutes,status,starts_at,ends_at").eq("provider_id",userId).order("created_at",{ascending:false}),
      supabase.from("bookings").select("provider_service_id").eq("provider_id",userId),
      supabase.from("post_services").select("provider_service_id,posts!inner(author_id)").eq("posts.author_id",userId),
      nextBusiness ? supabase.from("collaborators").select("id,display_name,internal_role,commercial_permissions").eq("business_id",nextBusiness.id).eq("is_active",true).is("archived_at",null) : Promise.resolve({data:[],error:null}),
    ]);
    const failed=[serviceResult,catalogResult,optionResult,promotionResult,packageResult,bookingResult,mediaResult,collaboratorResult].find(item=>item.error)?.error;
    if(failed){setFeedback(publicErrorMessage(failed,"Les offres n’ont pas pu être chargées."));setLoading(false);return;}
    setServices((serviceResult.data??[]) as unknown as CommercialService[]); setCatalog((catalogResult.data??[]) as unknown as CatalogService[]);
    setOptions((optionResult.data??[]) as ServiceOption[]); setPromotions((promotionResult.data??[]) as Promotion[]); setPackages((packageResult.data??[]) as Package[]); setCollaborators((collaboratorResult.data??[]) as Collaborator[]);
    setBookingCounts(countBy((bookingResult.data??[]) as Array<{provider_service_id:string}>,"provider_service_id")); setMediaCounts(countBy((mediaResult.data??[]) as Array<{provider_service_id:string}>,"provider_service_id")); setLoading(false);
  },[space,userId]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);

  const visibleServices=useMemo(()=>services.filter(item=>section==="published-offers"?item.status==="published":section==="service-drafts"?item.status==="draft":section==="archived-services"?item.status==="archived":section==="home-services"?item.location_modes.includes("client_address"):true),[section,services]);
  const activePromotions=promotions.filter(item=>item.status==="published"&&item.is_active&&new Date(item.starts_at)<=new Date()&&new Date(item.ends_at)>new Date()&&(item.max_uses===null||item.used_count<item.max_uses));

  async function saveService(event:FormEvent<HTMLFormElement>){
    event.preventDefault();const supabase=getSupabaseBrowserClient();if(!supabase)return;const form=event.currentTarget;const values=new FormData(form);const file=values.get("cover");let coverUrl=editing?.cover_url??null;let uploadedPath="";
    try{
      if(file instanceof File&&file.size){if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>8*1024*1024)throw new Error("Couverture JPEG, PNG ou WebP de 8 Mo maximum requise.");const extension=file.type==="image/png"?"png":file.type==="image/webp"?"webp":"jpg";uploadedPath=`${userId}/services/${crypto.randomUUID()}.${extension}`;const upload=await supabase.storage.from("provider-social-media").upload(uploadedPath,file,{contentType:file.type,cacheControl:"31536000"});if(upload.error)throw upload.error;coverUrl=supabase.storage.from("provider-social-media").getPublicUrl(uploadedPath).data.publicUrl;}
      if(!coverUrl)throw new Error("Ajoutez une photo de couverture.");
      const status=String(values.get("status")) as ServiceStatus; const locationModes=[values.get("salon")==="on"?"salon":"",values.get("home")==="on"?"client_address":""].filter(Boolean);
      if(!locationModes.length)throw new Error("Choisissez au moins un lieu.");
      const payload={provider_id:userId,business_id:space==="salon"?business?.id??null:null,service_id:String(values.get("serviceId")),title:String(values.get("title")).trim(),description:String(values.get("description")).trim(),cover_url:coverUrl,duration_minutes:Number(values.get("duration")),preparation_minutes:Number(values.get("preparation")||0),price_amount:Number(values.get("price")),currency:"XOF",pricing_mode:String(values.get("pricingMode")),price_from_amount:numberOrNull(values,"priceFrom"),location_modes:locationModes,home_price_amount:numberOrNull(values,"homePrice"),travel_fee_amount:Number(values.get("travelFee")||0),deposit_amount:Number(values.get("deposit")||0),cancellation_policy:String(values.get("cancellationPolicy")).trim(),client_instructions:String(values.get("instructions")).trim(),capacity:Number(values.get("capacity")||1),status};
      const result=editing?await supabase.from("provider_services").update(payload).eq("id",editing.id):await supabase.from("provider_services").insert(payload);
      if(result.error)throw result.error;setFeedback(status==="published"?"Prestation publiée et visible côté client.":"Brouillon enregistré.");setEditing(null);form.reset();await load();
    }catch(error){if(uploadedPath)await supabase.storage.from("provider-social-media").remove([uploadedPath]);setFeedback(publicErrorMessage(error,"La prestation n’a pas été enregistrée."));}
  }
  async function setStatus(service:CommercialService,status:ServiceStatus){const supabase=getSupabaseBrowserClient();if(!supabase)return;const {error}=await supabase.rpc("set_owned_service_status",{target_service_id:service.id,next_status:status});setFeedback(error?publicErrorMessage(error,"Le statut n’a pas été modifié."):`Offre ${statusLabels[status].toLocaleLowerCase("fr")}.`);if(!error)await load();}
  async function duplicate(service:CommercialService){const supabase=getSupabaseBrowserClient();if(!supabase)return;const {id,services:relation,archived_at,...copy}=service;void id;void relation;void archived_at;const {error}=await supabase.from("provider_services").insert({...copy,title:`${service.title} — copie`,status:"draft",cover_url:service.cover_url});setFeedback(error?"Duplication impossible.":"Copie créée en brouillon.");if(!error)await load();}
  async function saveOption(event:FormEvent<HTMLFormElement>){event.preventDefault();const supabase=getSupabaseBrowserClient();if(!supabase)return;const values=new FormData(event.currentTarget);const {error}=await supabase.from("service_options").insert({provider_service_id:String(values.get("serviceId")),name:String(values.get("name")).trim(),description:String(values.get("description")).trim()||null,price_amount:Number(values.get("price")||0),duration_minutes:Number(values.get("duration")||0),is_required:values.get("required")==="on",is_active:true});setFeedback(error?publicErrorMessage(error,"Option non créée."):"Option ajoutée.");if(!error){event.currentTarget.reset();await load();}}
  async function toggleOption(option:ServiceOption){const supabase=getSupabaseBrowserClient();if(!supabase)return;const{error}=await supabase.from("service_options").update({is_active:!option.is_active}).eq("id",option.id);setFeedback(error?"Option non modifiée.":"Option mise à jour.");if(!error)await load();}
  async function savePromotion(event:FormEvent<HTMLFormElement>){event.preventDefault();const supabase=getSupabaseBrowserClient();if(!supabase)return;const values=new FormData(event.currentTarget);const status=String(values.get("status"));const{error}=await supabase.from("promotions").insert({provider_id:userId,business_id:space==="salon"?business?.id??null:null,provider_service_id:String(values.get("serviceId"))||null,title:String(values.get("title")).trim(),description:String(values.get("description")).trim()||null,discount_type:String(values.get("discountType")),discount_value:Number(values.get("discountValue")),promotional_price_amount:numberOrNull(values,"promotionalPrice"),starts_at:new Date(String(values.get("startsAt"))).toISOString(),ends_at:new Date(String(values.get("endsAt"))).toISOString(),max_uses:numberOrNull(values,"maxUses"),new_clients_only:values.get("newClients")==="on",audience:values.get("newClients")==="on"?"new_clients":"all",promo_code:String(values.get("promoCode")).trim().toUpperCase()||null,status,is_active:status==="published"});setFeedback(error?publicErrorMessage(error,"Promotion non créée."):status==="published"?"Promotion publiée.":"Promotion enregistrée en brouillon.");if(!error){event.currentTarget.reset();await load();}}
  async function savePackage(event:FormEvent<HTMLFormElement>){event.preventDefault();const supabase=getSupabaseBrowserClient();if(!supabase)return;const values=new FormData(event.currentTarget);const selected=values.getAll("services").map(String);const{data,error}=await supabase.from("service_packages").insert({provider_id:userId,business_id:space==="salon"?business?.id??null:null,title:String(values.get("title")).trim(),description:String(values.get("description")).trim()||null,normal_price_amount:Number(values.get("normalPrice")),package_price_amount:Number(values.get("packagePrice")),duration_minutes:Number(values.get("duration")),starts_at:values.get("startsAt")?new Date(String(values.get("startsAt"))).toISOString():null,ends_at:values.get("endsAt")?new Date(String(values.get("endsAt"))).toISOString():null,status:String(values.get("status"))}).select("id").single();if(!error&&data&&selected.length){const items=await supabase.from("service_package_items").insert(selected.map(id=>({package_id:data.id,provider_service_id:id})));if(items.error){await supabase.from("service_packages").delete().eq("id",data.id);setFeedback("Le forfait n’a pas été associé aux prestations.");return;}}setFeedback(error?publicErrorMessage(error,"Forfait non créé."):"Forfait enregistré.");if(!error){event.currentTarget.reset();await load();}}
  async function savePermissions(event:FormEvent<HTMLFormElement>,person:Collaborator){event.preventDefault();const supabase=getSupabaseBrowserClient();if(!supabase)return;const values=new FormData(event.currentTarget);const permissions=commercialPermissions.filter(key=>values.get(key)==="on");const{error}=await supabase.from("collaborators").update({commercial_permissions:permissions}).eq("id",person.id);setFeedback(error?"Permissions non enregistrées.":"Permissions commerciales mises à jour.");if(!error)await load();}

  if(loading)return <section className="workspace-content"><div className="workspace-empty">Chargement des offres et tarifs…</div></section>;
  if(space==="salon"&&!business)return <section className="workspace-content"><div className="workspace-empty"><strong>Créez d’abord le profil du salon</strong><p>L’identité du salon est nécessaire avant d’ajouter des offres.</p><Link href="/salon/profile">Créer le salon</Link></div></section>;
  const showForm=section==="create-service"||Boolean(editing);
  return <section className="workspace-content commercial-offers">
    <div className="workspace-intro"><div><span>Offres & tarifs</span><h2>{sectionTitle(section)}</h2><p>Créez, tarifez, publiez et reliez vos prestations au Studio depuis un seul espace.</p></div><div className="workspace-status"><i/>Prix final calculé côté serveur</div></div>
    <div className="commercial-actions"><Link href={`/${space}/create-service`}>＋ Nouvelle prestation</Link><Link href={`/${space}/promotions`}>＋ Créer une promotion</Link><Link href={`/${space}/videos`}>▶ Publier une vidéo</Link></div>
    {feedback&&<p className="salon-feedback" role="status">{feedback}</p>}
    <div className="workspace-metrics"><article><span>Prestations actives</span><strong>{services.filter(item=>item.status==="published").length}</strong><small>visibles côté client</small></article><article><span>Promotions en cours</span><strong>{activePromotions.length}</strong><small>période et quota valides</small></article><article><span>Réservations</span><strong>{Object.values(bookingCounts).reduce((sum,value)=>sum+value,0)}</strong><small>sur vos offres</small></article></div>
    {showForm&&<ServiceForm catalog={catalog} editing={editing} onCancel={()=>setEditing(null)} onSubmit={saveService}/>} 
    {section==="options"&&<OptionsPanel services={services} options={options} onSubmit={saveOption} onToggle={toggleOption}/>} 
    {section==="promotions"&&<PromotionsPanel services={services.filter(item=>item.status==="published")} promotions={promotions} onSubmit={savePromotion}/>} 
    {section==="packages"&&<PackagesPanel services={services.filter(item=>item.status==="published")} packages={packages} onSubmit={savePackage}/>} 
    {section==="service-staff"&&<StaffPanel collaborators={collaborators} onSubmit={savePermissions}/>} 
    {section==="service-availability"&&<article className="workspace-panel commercial-panel"><h3>Disponibilités des offres</h3><p>Une offre publiée n’est proposée à la réservation que si l’Agenda ou les horaires du salon produisent un créneau réel.</p><Link className="commercial-primary" href={`/${space}/agenda`}>Configurer les disponibilités</Link></article>}
    {!showForm&&!["options","promotions","packages","service-staff","service-availability"].includes(section)&&<ServiceList services={visibleServices} options={options} promotions={promotions} bookingCounts={bookingCounts} mediaCounts={mediaCounts} onEdit={setEditing} onDuplicate={duplicate} onStatus={setStatus}/>} 
  </section>;
}

function ServiceForm({catalog,editing,onCancel,onSubmit}:{catalog:CatalogService[];editing:CommercialService|null;onCancel:()=>void;onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){return <article className="workspace-panel commercial-panel"><div className="panel-heading"><div><h3>{editing?"Modifier la prestation":"Créer une prestation"}</h3><p>Les champs commerciaux alimentent le profil public, le Studio et la réservation.</p></div>{editing&&<button onClick={onCancel}>Annuler</button>}</div><form className="commercial-form" onSubmit={onSubmit}>
  <label>Catégorie / sous-catégorie<select name="serviceId" required defaultValue={editing?.service_id??""}><option value="" disabled>Choisir une prestation de référence</option>{catalog.map(item=><option key={item.id} value={item.id}>{item.categories?.name??"Beauté"} · {item.name}</option>)}</select></label><label>Nom public<input name="title" required minLength={2} maxLength={120} defaultValue={editing?.title??""}/></label><label className="wide">Description<textarea name="description" required minLength={20} maxLength={2000} rows={4} defaultValue={editing?.description??""}/></label><label className="wide">Photo de couverture<input name="cover" type="file" accept="image/jpeg,image/png,image/webp" required={!editing?.cover_url}/>{editing?.cover_url&&<small>Conservez l’image actuelle ou choisissez-en une nouvelle.</small>}</label>
  <label>Tarification<select name="pricingMode" defaultValue={editing?.pricing_mode??"fixed"}><option value="fixed">Prix fixe</option><option value="from">À partir de</option><option value="variable">Variable</option><option value="option_based">Selon les options</option></select></label><label>Prix de base (FCFA)<input name="price" type="number" min="0" max="10000000" step="500" required defaultValue={editing?.price_amount??""}/></label><label>Prix « à partir de »<input name="priceFrom" type="number" min="0" step="500" defaultValue={editing?.price_from_amount??""}/></label><label>Durée (minutes)<input name="duration" type="number" min="15" max="720" step="15" required defaultValue={editing?.duration_minutes??60}/></label><label>Préparation (minutes)<input name="preparation" type="number" min="0" max="240" step="5" defaultValue={editing?.preparation_minutes??0}/></label><label>Capacité<input name="capacity" type="number" min="1" max="100" defaultValue={editing?.capacity??1}/></label>
  <fieldset><legend>Lieu</legend><label><input name="salon" type="checkbox" defaultChecked={editing?.location_modes.includes("salon")??true}/> Salon</label><label><input name="home" type="checkbox" defaultChecked={editing?.location_modes.includes("client_address")??false}/> Domicile</label></fieldset><label>Prix à domicile<input name="homePrice" type="number" min="0" step="500" defaultValue={editing?.home_price_amount??""}/></label><label>Frais de déplacement<input name="travelFee" type="number" min="0" step="500" defaultValue={editing?.travel_fee_amount??0}/></label><label>Acompte<input name="deposit" type="number" min="0" step="500" defaultValue={editing?.deposit_amount??0}/></label>
  <label className="wide">Politique d’annulation<textarea name="cancellationPolicy" required minLength={20} maxLength={1500} defaultValue={editing?.cancellation_policy??""}/></label><label className="wide">Instructions client<textarea name="instructions" required minLength={10} maxLength={1500} defaultValue={editing?.client_instructions??""}/></label><label>Enregistrement<select name="status" defaultValue={editing?.status??"draft"}><option value="draft">Enregistrer en brouillon</option><option value="published">Publier</option></select></label><button className="commercial-primary" type="submit">{editing?"Enregistrer les modifications":"Créer la prestation"}</button>
  </form></article>}

function ServiceList({services,options,promotions,bookingCounts,mediaCounts,onEdit,onDuplicate,onStatus}:{services:CommercialService[];options:ServiceOption[];promotions:Promotion[];bookingCounts:Record<string,number>;mediaCounts:Record<string,number>;onEdit:(s:CommercialService)=>void;onDuplicate:(s:CommercialService)=>Promise<void>;onStatus:(s:CommercialService,status:ServiceStatus)=>Promise<void>}){return <article className="workspace-panel commercial-panel"><div className="panel-heading"><div><h3>Mes prestations</h3><p>{services.length} offre{services.length>1?"s":""} dans cette vue.</p></div></div><div className="commercial-service-grid">{services.map(service=>{const promo=promotions.find(item=>item.provider_service_id===service.id&&item.status==="published"&&new Date(item.ends_at)>new Date());return <article className="commercial-service-card" key={service.id}>{service.cover_url?<Image src={service.cover_url} alt="" width={420} height={220} unoptimized/>:<div className="service-cover-placeholder">Mata Beauty</div>}<div><span className={`service-status ${service.status}`}>{statusLabels[service.status]}</span><small>{service.services?.categories?.name??"Beauté"}</small><h4>{service.title}</h4><p>{service.description}</p><div className="service-price">{promo&&<del>{money(service.price_amount)}</del>}<strong>{promo?money(promotionPrice(service.price_amount,promo)):money(service.price_amount)}</strong><small>{service.duration_minutes} min · {service.location_modes.includes("client_address")?"Salon & domicile":"Salon"}</small></div><ul><li>{bookingCounts[service.id]??0} réservation(s)</li><li>{mediaCounts[service.id]??0} vidéo(s) associée(s)</li><li>{options.filter(item=>item.provider_service_id===service.id&&item.is_active).length} option(s)</li></ul><div className="service-card-actions"><button onClick={()=>onEdit(service)}>Modifier</button><button onClick={()=>void onDuplicate(service)}>Dupliquer</button>{service.status!=="published"&&service.status!=="archived"&&<button onClick={()=>void onStatus(service,"published")}>Publier</button>}{service.status==="published"&&<button onClick={()=>void onStatus(service,"paused")}>Désactiver</button>}{service.status!=="archived"&&<button onClick={()=>void onStatus(service,"archived")}>Archiver</button>}<Link href={`/service/${service.id}`} target="_blank">Voir côté client</Link></div></div></article>})}{services.length===0&&<div className="workspace-empty"><strong>Aucune offre dans cette vue</strong><p>Créez une prestation ou changez son statut.</p></div>}</div></article>}

function OptionsPanel({services,options,onSubmit,onToggle}:{services:CommercialService[];options:ServiceOption[];onSubmit:(e:FormEvent<HTMLFormElement>)=>void;onToggle:(o:ServiceOption)=>Promise<void>}){return <div className="commercial-columns"><article className="workspace-panel commercial-panel"><h3>Nouvelle option ou supplément</h3><form className="commercial-form one-column" onSubmit={onSubmit}><label>Prestation<select name="serviceId" required defaultValue=""><option value="" disabled>Choisir</option>{services.map(item=><option value={item.id} key={item.id}>{item.title}</option>)}</select></label><label>Nom<input name="name" required minLength={2}/></label><label>Description<textarea name="description" maxLength={1000}/></label><label>Prix supplémentaire<input name="price" type="number" min="0" step="500" required/></label><label>Durée supplémentaire<input name="duration" type="number" min="0" max="360" step="5" defaultValue="0"/></label><label><input name="required" type="checkbox"/> Option obligatoire</label><button className="commercial-primary">Ajouter l’option</button></form></article><article className="workspace-panel commercial-panel"><h3>Options existantes</h3><div className="commercial-list">{options.map(item=><div key={item.id}><span><strong>{item.name}</strong><small>{money(item.price_amount)} · +{item.duration_minutes} min · {item.is_required?"obligatoire":"facultative"}</small></span><button onClick={()=>void onToggle(item)}>{item.is_active?"Désactiver":"Activer"}</button></div>)}</div></article></div>}

function PromotionsPanel({services,promotions,onSubmit}:{services:CommercialService[];promotions:Promotion[];onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){return <div className="commercial-columns"><article className="workspace-panel commercial-panel"><h3>Créer une promotion</h3><form className="commercial-form one-column" onSubmit={onSubmit}><label>Titre<input name="title" required minLength={2}/></label><label>Prestation<select name="serviceId" required defaultValue=""><option value="" disabled>Choisir</option>{services.map(item=><option value={item.id} key={item.id}>{item.title}</option>)}</select></label><label>Description<textarea name="description" maxLength={1000}/></label><label>Type<select name="discountType"><option value="percentage">Pourcentage</option><option value="fixed">Montant</option></select></label><label>Réduction<input name="discountValue" type="number" min="1" required/></label><label>Prix promotionnel explicite<input name="promotionalPrice" type="number" min="0" step="500"/></label><label>Début<input name="startsAt" type="datetime-local" required/></label><label>Fin<input name="endsAt" type="datetime-local" required/></label><label>Utilisations maximum<input name="maxUses" type="number" min="1"/></label><label>Code promo<input name="promoCode" maxLength={40}/></label><label><input name="newClients" type="checkbox"/> Nouveaux clients seulement</label><label>Statut<select name="status"><option value="draft">Brouillon</option><option value="published">Publier</option></select></label><button className="commercial-primary">Créer la promotion</button></form></article><article className="workspace-panel commercial-panel"><h3>Promotions</h3><div className="commercial-list">{promotions.map(item=><div key={item.id}><span><strong>{item.title}</strong><small>{item.discount_type==="percentage"?`−${item.discount_value}%`:`−${money(item.discount_value)}`} · {new Date(item.starts_at).toLocaleDateString("fr-FR")} → {new Date(item.ends_at).toLocaleDateString("fr-FR")} · {item.status}</small></span></div>)}</div></article></div>}

function PackagesPanel({services,packages,onSubmit}:{services:CommercialService[];packages:Package[];onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){return <div className="commercial-columns"><article className="workspace-panel commercial-panel"><h3>Créer un forfait</h3><form className="commercial-form one-column" onSubmit={onSubmit}><label>Titre<input name="title" required minLength={2}/></label><label>Description<textarea name="description" maxLength={2000}/></label><fieldset><legend>Prestations incluses</legend>{services.map(item=><label key={item.id}><input type="checkbox" name="services" value={item.id}/>{item.title}</label>)}</fieldset><label>Prix normal<input name="normalPrice" type="number" min="0" required/></label><label>Prix forfaitaire<input name="packagePrice" type="number" min="0" required/></label><label>Durée totale<input name="duration" type="number" min="15" max="1440" required/></label><label>Début<input name="startsAt" type="datetime-local"/></label><label>Fin<input name="endsAt" type="datetime-local"/></label><label>Statut<select name="status"><option value="draft">Brouillon</option><option value="published">Publié</option></select></label><button className="commercial-primary">Enregistrer le forfait</button></form></article><article className="workspace-panel commercial-panel"><h3>Forfaits existants</h3><div className="commercial-list">{packages.map(item=><div key={item.id}><span><strong>{item.title}</strong><small><del>{money(item.normal_price_amount)}</del> {money(item.package_price_amount)} · {item.duration_minutes} min · {item.status}</small></span></div>)}</div></article></div>}

function StaffPanel({collaborators,onSubmit}:{collaborators:Collaborator[];onSubmit:(event:FormEvent<HTMLFormElement>,person:Collaborator)=>Promise<void>}){return <article className="workspace-panel commercial-panel"><h3>Permissions commerciales de l’équipe</h3><p>Un membre sans permission ne peut pas modifier les prestations ni les prix, même par requête directe.</p><div className="staff-permission-grid">{collaborators.map(person=><form key={person.id} onSubmit={event=>void onSubmit(event,person)}><strong>{person.display_name}</strong><small>{person.internal_role}</small>{commercialPermissions.map(permission=><label key={permission}><input type="checkbox" name={permission} defaultChecked={person.commercial_permissions.includes(permission)}/>{permission}</label>)}<button className="commercial-primary">Enregistrer</button></form>)}</div></article>}

function countBy<T extends Record<K,string>,K extends keyof T>(rows:T[],key:K){return rows.reduce<Record<string,number>>((result,row)=>({...result,[row[key]]:(result[row[key]]??0)+1}),{});}
function numberOrNull(values:FormData,key:string){const value=String(values.get(key)??"").trim();return value?Number(value):null;}
function money(value:number){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:"XOF",maximumFractionDigits:0}).format(value);}
function promotionPrice(price:number,promotion:Promotion){if(promotion.promotional_price_amount!==null)return promotion.promotional_price_amount;return promotion.discount_type==="percentage"?Math.max(0,Math.round(price*(1-promotion.discount_value/100))):Math.max(0,price-promotion.discount_value);}
function sectionTitle(section:OfferSection){return ({services:"Mes prestations","create-service":"Créer une prestation",pricing:"Tarifs",options:"Options & suppléments",promotions:"Promotions",packages:"Forfaits","home-services":"Prestations à domicile","published-offers":"Offres publiées","service-drafts":"Brouillons","archived-services":"Archivées","service-staff":"Membres affectés","service-availability":"Disponibilités"})[section]??"Offres & tarifs";}
