"use client";

import Image from "next/image";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import type { WorkspaceModule } from "@/lib/navigation/spaces";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { publicErrorMessage } from "@/lib/ui/public-error";

type Business = { id: string; name: string; slug: string; description: string | null; phone: string | null; address: string; city: string; area: string | null; latitude: number | null; longitude: number | null; logo_url: string | null; cover_url: string | null; status: string; is_active: boolean; archived_at: string | null };
type Service = { id: string; service_id: string; title: string; description: string | null; duration_minutes: number; price_amount: number; currency: string; is_active: boolean; archived_at: string | null };
type Collaborator = { id: string; display_name: string; title: string | null; internal_role: string; is_bookable: boolean; is_active: boolean; archived_at: string | null };
type Invitation = { id: string; email: string; internal_role: string; status: string; expires_at: string };
type Booking = { id: string; starts_at: string; ends_at: string; status: string; total_amount: number; currency: string; collaborator_id: string | null; provider_service_id: string };
type Hours = { id: string; weekday: number; opens_at: string | null; closes_at: string | null; is_closed: boolean };
type Closure = { id: string; starts_at: string; ends_at: string; reason: string | null };
type Media = { id: string; storage_path: string; media_type: string; sort_order: number };
type CatalogService = { id: string; name: string };
type Review = { id: string; rating: number; comment: string | null; provider_reply: string | null; created_at: string };

const days = ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"];
const supportedModules = new Set(["dashboard", "profile", "team", "services", "agenda", "bookings", "revenue", "statistics", "reviews", "portfolio", "settings"]);

export function SalonControlCenter({ module, userId }: { module: WorkspaceModule; userId: string }) {
  const [business, setBusiness] = useState<Business | null>(null);
  const [services, setServices] = useState<Service[]>([]);
  const [collaborators, setCollaborators] = useState<Collaborator[]>([]);
  const [invitations, setInvitations] = useState<Invitation[]>([]);
  const [bookings, setBookings] = useState<Booking[]>([]);
  const [hours, setHours] = useState<Hours[]>([]);
  const [closures, setClosures] = useState<Closure[]>([]);
  const [media, setMedia] = useState<Media[]>([]);
  const [catalog, setCatalog] = useState<CatalogService[]>([]);
  const [reviews, setReviews] = useState<Review[]>([]);
  const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  const [feedback, setFeedback] = useState("");

  const load = useCallback(async () => {
    const supabase = getSupabaseBrowserClient();
    if (!supabase) return;
    setState("loading");
    const { data: businessData, error } = await supabase.from("businesses").select("id,name,slug,description,phone,address,city,area,latitude,longitude,logo_url,cover_url,status,is_active,archived_at").eq("owner_id", userId).is("archived_at", null).order("created_at").limit(1).maybeSingle();
    if (error) { setState("error"); setFeedback(publicErrorMessage(error, "Le salon n’a pas pu être chargé.")); return; }
    const nextBusiness = businessData as Business | null; setBusiness(nextBusiness);
    const { data: catalogData } = await supabase.from("services").select("id,name").eq("is_active", true).order("name"); setCatalog((catalogData ?? []) as CatalogService[]);
    if (!nextBusiness) { setServices([]); setCollaborators([]); setInvitations([]); setBookings([]); setHours([]); setClosures([]); setMedia([]); setState("ready"); return; }
    const [serviceResult, collaboratorResult, invitationResult, bookingResult, hoursResult, closureResult, mediaResult, reviewResult] = await Promise.all([
      supabase.from("provider_services").select("id,service_id,title,description,duration_minutes,price_amount,currency,is_active,archived_at").eq("business_id", nextBusiness.id).is("archived_at", null).order("title"),
      supabase.from("collaborators").select("id,display_name,title,internal_role,is_bookable,is_active,archived_at").eq("business_id", nextBusiness.id).is("archived_at", null).order("display_name"),
      supabase.from("business_invitations").select("id,email,internal_role,status,expires_at").eq("business_id", nextBusiness.id).eq("status", "pending").order("created_at", { ascending: false }),
      supabase.from("bookings").select("id,starts_at,ends_at,status,total_amount,currency,collaborator_id,provider_service_id").eq("business_id", nextBusiness.id).order("starts_at", { ascending: false }).limit(200),
      supabase.from("business_hours").select("id,weekday,opens_at,closes_at,is_closed").eq("business_id", nextBusiness.id).order("weekday"),
      supabase.from("business_closures").select("id,starts_at,ends_at,reason").eq("business_id", nextBusiness.id).order("starts_at"),
      supabase.from("business_media").select("id,storage_path,media_type,sort_order").eq("business_id", nextBusiness.id).order("sort_order"),
      supabase.from("reviews").select("id,rating,comment,provider_reply,created_at").eq("provider_id", userId).eq("is_visible", true).order("created_at", { ascending: false }),
    ]);
    const firstError = [serviceResult, collaboratorResult, invitationResult, bookingResult, hoursResult, closureResult, mediaResult, reviewResult].find((result) => result.error)?.error;
    if (firstError) { setState("error"); setFeedback(publicErrorMessage(firstError, "Certaines données du salon sont indisponibles.")); return; }
    setServices((serviceResult.data ?? []) as Service[]); setCollaborators((collaboratorResult.data ?? []) as Collaborator[]); setInvitations((invitationResult.data ?? []) as Invitation[]); setBookings((bookingResult.data ?? []) as Booking[]); setHours((hoursResult.data ?? []) as Hours[]); setClosures((closureResult.data ?? []) as Closure[]); setMedia((mediaResult.data ?? []) as Media[]); setReviews((reviewResult.data ?? []) as Review[]); setState("ready");
  }, [userId]);

  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const today = useMemo(() => bookings.filter((booking) => new Date(booking.starts_at).toDateString() === new Date().toDateString()), [bookings]);
  const revenue = useMemo(() => bookings.filter((booking) => ["completed", "confirmed"].includes(booking.status)).reduce((sum, booking) => sum + booking.total_amount, 0), [bookings]);

  async function submitBusiness(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const supabase = getSupabaseBrowserClient(); if (!supabase) return;
    const values = new FormData(event.currentTarget); const name = String(values.get("name") ?? "").trim();
    const payload = { owner_id: userId, name, slug: business?.slug ?? `${slugify(name)}-${userId.slice(0, 6)}`, description: nullable(values, "description"), phone: nullable(values, "phone"), address: String(values.get("address") ?? "").trim(), city: String(values.get("city") ?? "Dakar").trim(), area: nullable(values, "area"), latitude: numberOrNull(values, "latitude"), longitude: numberOrNull(values, "longitude") };
    const result = business ? await supabase.from("businesses").update(payload).eq("id", business.id) : await supabase.from("businesses").insert({ ...payload, business_type: "salon", status: "draft" });
    setFeedback(result.error ? publicErrorMessage(result.error, "Enregistrement impossible.") : "Informations du salon enregistrées."); if (!result.error) await load();
  }

  async function addService(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!business) return; const supabase = getSupabaseBrowserClient(); if (!supabase) return; const values = new FormData(event.currentTarget);
    const result = await supabase.from("provider_services").insert({ provider_id: userId, business_id: business.id, service_id: String(values.get("serviceId")), title: String(values.get("title")).trim(), description: nullable(values, "description"), duration_minutes: Number(values.get("duration")), price_amount: Number(values.get("price")), currency: "XOF", is_active: true });
    setFeedback(result.error ? publicErrorMessage(result.error, "La prestation n’a pas été créée.") : "Prestation ajoutée au catalogue du salon."); if (!result.error) { event.currentTarget.reset(); await load(); }
  }

  async function toggleService(service: Service) { const supabase = getSupabaseBrowserClient(); if (!supabase) return; const { error } = await supabase.from("provider_services").update({ is_active: !service.is_active }).eq("id", service.id); setFeedback(error ? "La prestation n’a pas été modifiée." : "Prestation mise à jour."); if (!error) await load(); }
  async function archiveService(service: Service) { if (!window.confirm(`Archiver « ${service.title} » ?`)) return; const supabase = getSupabaseBrowserClient(); if (!supabase) return; const { error } = await supabase.from("provider_services").update({ is_active: false, archived_at: new Date().toISOString() }).eq("id", service.id); setFeedback(error ? "Archivage impossible." : "Prestation archivée sans effacer son historique."); if (!error) await load(); }

  async function addCollaborator(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!business) return; const supabase = getSupabaseBrowserClient(); if (!supabase) return; const values = new FormData(event.currentTarget); const { error } = await supabase.from("collaborators").insert({ business_id: business.id, display_name: String(values.get("name")).trim(), title: nullable(values, "title"), internal_role: String(values.get("role")), is_bookable: values.get("bookable") === "on", is_active: true }); setFeedback(error ? publicErrorMessage(error, "Ajout impossible.") : "Collaborateur ajouté."); if (!error) { event.currentTarget.reset(); await load(); } }
  async function invite(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!business) return; const supabase = getSupabaseBrowserClient(); if (!supabase) return; const values = new FormData(event.currentTarget); const { error } = await supabase.from("business_invitations").insert({ business_id: business.id, email: String(values.get("email")).trim().toLowerCase(), internal_role: String(values.get("role")), invited_by: userId }); setFeedback(error ? publicErrorMessage(error, "Invitation impossible.") : "Invitation enregistrée pour sept jours."); if (!error) { event.currentTarget.reset(); await load(); } }
  async function archiveCollaborator(person: Collaborator) { if (!window.confirm(`Retirer ${person.display_name} de l’équipe ?`)) return; const supabase = getSupabaseBrowserClient(); if (!supabase) return; const { error } = await supabase.from("collaborators").update({ is_active: false, archived_at: new Date().toISOString() }).eq("id", person.id); setFeedback(error ? "Retrait impossible." : "Collaborateur archivé."); if (!error) await load(); }

  async function saveHours(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!business) return; const supabase = getSupabaseBrowserClient(); if (!supabase) return; const values = new FormData(event.currentTarget); const rows = days.map((_, weekday) => { const closed = values.get(`closed-${weekday}`) === "on"; return { business_id: business.id, weekday, is_closed: closed, opens_at: closed ? null : String(values.get(`open-${weekday}`) || "09:00"), closes_at: closed ? null : String(values.get(`close-${weekday}`) || "18:00") }; }); const { error } = await supabase.from("business_hours").upsert(rows, { onConflict: "business_id,weekday" }); setFeedback(error ? publicErrorMessage(error, "Horaires non enregistrés.") : "Horaires enregistrés."); if (!error) await load(); }
  async function addClosure(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!business) return; const supabase = getSupabaseBrowserClient(); if (!supabase) return; const values = new FormData(event.currentTarget); const { error } = await supabase.from("business_closures").insert({ business_id: business.id, starts_at: new Date(String(values.get("startsAt"))).toISOString(), ends_at: new Date(String(values.get("endsAt"))).toISOString(), reason: nullable(values, "reason") }); setFeedback(error ? publicErrorMessage(error, "Fermeture non enregistrée.") : "Fermeture exceptionnelle ajoutée."); if (!error) { event.currentTarget.reset(); await load(); } }
  async function removeClosure(id: string) { const supabase = getSupabaseBrowserClient(); if (!supabase) return; const { error } = await supabase.from("business_closures").delete().eq("id", id); setFeedback(error ? "Suppression impossible." : "Fermeture retirée."); if (!error) await load(); }

  async function uploadMedia(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!business) return; const supabase = getSupabaseBrowserClient(); if (!supabase) return; const values = new FormData(event.currentTarget); const file = values.get("file"); const mediaType = String(values.get("mediaType")); if (!(file instanceof File) || !file.size) return; if (!["image/jpeg", "image/png", "image/webp"].includes(file.type) || file.size > 12 * 1024 * 1024) { setFeedback("Image JPEG, PNG ou WebP de 12 Mo maximum requise."); return; } const extension = file.type === "image/png" ? "png" : file.type === "image/webp" ? "webp" : "jpg"; const path = `${business.id}/${mediaType}-${crypto.randomUUID()}.${extension}`; const upload = await supabase.storage.from("business-media").upload(path, file, { contentType: file.type, cacheControl: "31536000", upsert: false }); if (upload.error) { setFeedback(publicErrorMessage(upload.error, "Envoi impossible.")); return; } const publicUrl = supabase.storage.from("business-media").getPublicUrl(path).data.publicUrl; const row = await supabase.from("business_media").insert({ business_id: business.id, storage_path: path, media_type: mediaType, sort_order: media.length }); if (!row.error && mediaType !== "gallery") await supabase.from("businesses").update(mediaType === "logo" ? { logo_url: publicUrl } : { cover_url: publicUrl }).eq("id", business.id); if (row.error) { await supabase.storage.from("business-media").remove([path]); setFeedback("Le média n’a pas pu être enregistré."); } else { setFeedback("Média du salon mis à jour."); event.currentTarget.reset(); await load(); } }
  async function removeMedia(item: Media) { const supabase = getSupabaseBrowserClient(); if (!supabase) return; const storage = await supabase.storage.from("business-media").remove([item.storage_path]); if (storage.error) { setFeedback("Le fichier n’a pas pu être retiré."); return; } const { error } = await supabase.from("business_media").delete().eq("id", item.id); setFeedback(error ? "Le média n’a pas pu être archivé." : "Média retiré."); if (!error) await load(); }
  async function updateBooking(id: string, status: "confirmed" | "in_progress" | "completed" | "cancelled_by_provider") { const supabase = getSupabaseBrowserClient(); if (!supabase) return; const { error } = await supabase.from("bookings").update({ status }).eq("id", id); setFeedback(error ? publicErrorMessage(error, "La réservation n’a pas été modifiée.") : "Réservation mise à jour."); if (!error) await load(); }

  if (state === "loading") return <section className="workspace-content"><div className="workspace-empty">Chargement sécurisé du salon…</div></section>;
  if (state === "error") return <section className="workspace-content"><div className="workspace-empty"><strong>Données indisponibles</strong><p>{feedback}</p><button onClick={() => void load()}>Réessayer</button></div></section>;
  if (!business || module.key === "profile") return <section className="workspace-content"><SalonHero title={business ? "Profil du salon" : "Créer votre salon"} description="Identité, coordonnées et localisation réellement publiées." />{feedback && <p className="salon-feedback" role="status">{feedback}</p>}<article className="workspace-panel salon-panel"><form className="salon-form" onSubmit={(event) => void submitBusiness(event)}><label>Nom<input name="name" required minLength={2} maxLength={120} defaultValue={business?.name ?? ""} /></label><label>Téléphone<input name="phone" type="tel" defaultValue={business?.phone ?? ""} /></label><label className="wide">Description<textarea name="description" maxLength={3000} rows={4} defaultValue={business?.description ?? ""} /></label><label className="wide">Adresse<input name="address" required defaultValue={business?.address ?? ""} /></label><label>Ville<input name="city" required defaultValue={business?.city ?? "Dakar"} /></label><label>Quartier / zone<input name="area" defaultValue={business?.area ?? ""} /></label><label>Latitude<input name="latitude" type="number" step="0.000001" defaultValue={business?.latitude ?? ""} /></label><label>Longitude<input name="longitude" type="number" step="0.000001" defaultValue={business?.longitude ?? ""} /></label><button className="salon-primary">{business ? "Enregistrer les modifications" : "Créer le salon"}</button></form></article></section>;

  if (module.key === "services") return <section className="workspace-content"><SalonHero title="Prestations" description="Prix et durées sont enregistrés côté serveur et recopiés dans chaque réservation." />{feedback && <p className="salon-feedback" role="status">{feedback}</p>}<article className="workspace-panel salon-panel"><form className="salon-form" onSubmit={(event) => void addService(event)}><label>Prestation de référence<select name="serviceId" required defaultValue=""><option value="" disabled>Choisir</option>{catalog.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Nom public<input name="title" required minLength={2} maxLength={120} /></label><label>Durée (minutes)<input name="duration" type="number" min="15" max="720" step="15" required /></label><label>Prix (FCFA)<input name="price" type="number" min="0" max="10000000" required /></label><label className="wide">Description<textarea name="description" maxLength={2000} /></label><button className="salon-primary">Ajouter la prestation</button></form><div className="salon-list">{services.map((service) => <div key={service.id}><div><strong>{service.title}</strong><small>{service.duration_minutes} min · {money(service.price_amount)} · {service.is_active ? "Active" : "Inactive"}</small></div><button onClick={() => void toggleService(service)}>{service.is_active ? "Désactiver" : "Activer"}</button><button className="danger" onClick={() => void archiveService(service)}>Archiver</button></div>)}{services.length === 0 && <p>Aucune prestation. Ajoutez la première offre réservable.</p>}</div></article></section>;

  if (module.key === "team") return <section className="workspace-content"><SalonHero title="Équipe" description="Membres, rôles internes et invitations limités à ce salon." />{feedback && <p className="salon-feedback" role="status">{feedback}</p>}<div className="salon-two-columns"><article className="workspace-panel salon-panel"><h3>Ajouter un membre</h3><form className="salon-form" onSubmit={(event) => void addCollaborator(event)}><label>Nom<input name="name" required minLength={2} /></label><label>Fonction<input name="title" /></label><label>Rôle<select name="role"><option value="member">Membre</option><option value="reception">Réception</option><option value="manager">Manager</option></select></label><label className="check"><input name="bookable" type="checkbox" defaultChecked /> Réservable</label><button className="salon-primary">Ajouter</button></form><div className="salon-list">{collaborators.map((person) => <div key={person.id}><div><strong>{person.display_name}</strong><small>{person.title || "Équipe"} · {person.internal_role}</small></div><button className="danger" onClick={() => void archiveCollaborator(person)}>Retirer</button></div>)}</div></article><article className="workspace-panel salon-panel"><h3>Inviter par e-mail</h3><form className="salon-form" onSubmit={(event) => void invite(event)}><label className="wide">E-mail<input name="email" type="email" required /></label><label>Rôle<select name="role"><option value="member">Membre</option><option value="reception">Réception</option><option value="manager">Manager</option></select></label><button className="salon-primary">Créer l’invitation</button></form><div className="salon-list">{invitations.map((item) => <div key={item.id}><div><strong>{item.email}</strong><small>{item.internal_role} · expire le {new Date(item.expires_at).toLocaleDateString("fr-FR")}</small></div></div>)}</div></article></div></section>;

  if (module.key === "agenda") return <section className="workspace-content"><SalonHero title="Agenda du salon" description="Horaires réguliers, fermetures exceptionnelles et rendez-vous réels." />{feedback && <p className="salon-feedback" role="status">{feedback}</p>}<div className="salon-two-columns"><article className="workspace-panel salon-panel"><h3>Horaires d’ouverture</h3><form onSubmit={(event) => void saveHours(event)}>{days.map((day, weekday) => { const current = hours.find((item) => item.weekday === weekday); return <div className="hours-row" key={day}><strong>{day}</strong><input aria-label={`Ouverture ${day}`} name={`open-${weekday}`} type="time" defaultValue={current?.opens_at?.slice(0, 5) ?? "09:00"} /><input aria-label={`Fermeture ${day}`} name={`close-${weekday}`} type="time" defaultValue={current?.closes_at?.slice(0, 5) ?? "18:00"} /><label><input name={`closed-${weekday}`} type="checkbox" defaultChecked={current?.is_closed ?? weekday === 0} /> Fermé</label></div>; })}<button className="salon-primary">Enregistrer les horaires</button></form></article><article className="workspace-panel salon-panel"><h3>Fermetures exceptionnelles</h3><form className="salon-form" onSubmit={(event) => void addClosure(event)}><label>Début<input name="startsAt" type="datetime-local" required /></label><label>Fin<input name="endsAt" type="datetime-local" required /></label><label className="wide">Motif<input name="reason" maxLength={240} /></label><button className="salon-primary">Ajouter</button></form><div className="salon-list">{closures.map((item) => <div key={item.id}><div><strong>{item.reason || "Fermeture"}</strong><small>{date(item.starts_at)} → {date(item.ends_at)}</small></div><button onClick={() => void removeClosure(item.id)}>Retirer</button></div>)}</div></article></div></section>;

  if (module.key === "portfolio") return <section className="workspace-content"><SalonHero title="Galerie du salon" description="Logo, couverture et réalisations contrôlés par type et par taille." />{feedback && <p className="salon-feedback" role="status">{feedback}</p>}<article className="workspace-panel salon-panel"><form className="salon-form" onSubmit={(event) => void uploadMedia(event)}><label>Type<select name="mediaType"><option value="logo">Logo</option><option value="cover">Couverture</option><option value="gallery">Galerie</option></select></label><label className="wide">Image<input name="file" type="file" accept="image/jpeg,image/png,image/webp" required /></label><button className="salon-primary">Envoyer l’image</button></form><div className="salon-media-grid">{media.map((item) => { const url = getSupabaseBrowserClient()?.storage.from("business-media").getPublicUrl(item.storage_path).data.publicUrl ?? ""; return <article key={item.id}>{url && <Image src={url} alt={`${item.media_type} du salon`} width={360} height={220} unoptimized />}<span>{item.media_type}</span><button onClick={() => void removeMedia(item)}>Retirer</button></article>; })}</div></article></section>;

  if (module.key === "reviews") return <section className="workspace-content"><SalonHero title="Avis du salon" description="Avis issus de rendez-vous terminés, visibles sans données privées de la cliente." /><article className="workspace-panel salon-panel"><div className="salon-list">{reviews.map((review) => <div key={review.id}><div><strong>{"★".repeat(review.rating)}{"☆".repeat(5 - review.rating)}</strong><small>{review.comment || "Avis sans commentaire"} · {new Date(review.created_at).toLocaleDateString("fr-FR")}</small>{review.provider_reply && <small>Réponse : {review.provider_reply}</small>}</div></div>)}{reviews.length === 0 && <p>Aucun avis reçu pour le moment.</p>}</div></article></section>;

  if (["bookings", "revenue", "statistics", "dashboard"].includes(module.key)) return <section className="workspace-content"><SalonHero title={module.key === "dashboard" ? business.name : module.label} description="Activité calculée à partir des réservations visibles par les politiques RLS." /><div className="workspace-metrics"><article><span>Aujourd’hui</span><strong>{today.length}</strong><small>rendez-vous</small></article><article><span>Chiffre d’affaires suivi</span><strong>{money(revenue)}</strong><small>réservations confirmées ou terminées</small></article><article><span>Équipe active</span><strong>{collaborators.filter((item) => item.is_active).length}</strong><small>collaborateurs</small></article></div>{feedback && <p className="salon-feedback" role="status">{feedback}</p>}<article className="workspace-panel salon-panel"><h3>Réservations du salon</h3><div className="salon-list">{bookings.map((booking) => <div key={booking.id}><div><strong>{date(booking.starts_at)}</strong><small>{money(booking.total_amount)} · {booking.status.replaceAll("_", " ")}</small></div>{booking.status === "pending" && <button onClick={() => void updateBooking(booking.id, "confirmed")}>Confirmer</button>}{booking.status === "confirmed" && <button onClick={() => void updateBooking(booking.id, "in_progress")}>Démarrer</button>}{booking.status === "in_progress" && <button onClick={() => void updateBooking(booking.id, "completed")}>Terminer</button>}{["pending", "confirmed"].includes(booking.status) && <button className="danger" onClick={() => void updateBooking(booking.id, "cancelled_by_provider")}>Annuler</button>}</div>)}{bookings.length === 0 && <p>Aucune réservation pour ce salon.</p>}</div></article></section>;

  if (module.key === "settings") return <section className="workspace-content"><SalonHero title="Paramètres du salon" description="Publication et archivage sans suppression de l’historique." />{feedback && <p className="salon-feedback" role="status">{feedback}</p>}<article className="workspace-panel salon-panel"><div className="salon-list"><div><div><strong>Visibilité du salon</strong><small>{business.is_active ? "Actif" : "Inactif"} · validation {business.status}</small></div><button onClick={async () => { const supabase = getSupabaseBrowserClient(); if (!supabase) return; const { error } = await supabase.from("businesses").update({ is_active: !business.is_active }).eq("id", business.id); setFeedback(error ? "Modification impossible." : "Visibilité mise à jour."); if (!error) await load(); }}>{business.is_active ? "Désactiver" : "Réactiver"}</button></div><div><div><strong>Archiver ce salon</strong><small>Les réservations, montants et journaux restent conservés.</small></div><button className="danger" onClick={async () => { if (!window.confirm("Archiver le salon et désactiver ses prestations ?")) return; const supabase = getSupabaseBrowserClient(); if (!supabase) return; const { error } = await supabase.rpc("archive_owned_business", { target_business_id: business.id }); setFeedback(error ? publicErrorMessage(error, "Archivage impossible.") : "Salon archivé."); if (!error) await load(); }}>Archiver</button></div></div></article></section>;

  if (!supportedModules.has(module.key)) return null;
  return <section className="workspace-content"><SalonHero title={module.label} description={module.description} /><article className="workspace-panel salon-panel"><p>Les données de ce module sont consolidées dans les espaces Agenda, Réservations, Équipe et Prestations.</p></article></section>;
}

function SalonHero({ title, description }: { title: string; description: string }) { return <div className="workspace-intro"><div><span>Gestion Salon</span><h2>{title}</h2><p>{description}</p></div><div className="workspace-status"><i />Données réelles · Supabase</div></div>; }
function nullable(values: FormData, key: string) { const value = String(values.get(key) ?? "").trim(); return value || null; }
function numberOrNull(values: FormData, key: string) { const value = String(values.get(key) ?? "").trim(); return value ? Number(value) : null; }
function slugify(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "salon"; }
function money(value: number) { return new Intl.NumberFormat("fr-FR", { style: "currency", currency: "XOF", maximumFractionDigits: 0 }).format(value); }
function date(value: string) { return new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
