import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";
import { createClient } from "@supabase/supabase-js";

type PublicService = { id: string; title: string; description: string | null; duration_minutes: number; price_amount: number; cover_url:string|null; deposit_amount:number; cancellation_policy:string|null; client_instructions:string|null; location_modes:string[]; service_options:{id:string;name:string;price_amount:number;duration_minutes:number;is_required:boolean}[]; promotions:{id:string;title:string;discount_type:"percentage"|"fixed";discount_value:number;promotional_price_amount:number|null;ends_at:string}[]; provider_profiles: { business_name: string; city: string; average_rating:number; review_count:number } | null };
async function loadService(id: string) { const url = process.env.NEXT_PUBLIC_SUPABASE_URL, key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY; if (!url || !key) return null; const client = createClient(url, key, { auth: { persistSession: false } }); const now=new Date().toISOString(); const { data } = await client.from("provider_services").select("id,title,description,duration_minutes,price_amount,cover_url,deposit_amount,cancellation_policy,client_instructions,location_modes,service_options(id,name,price_amount,duration_minutes,is_required),promotions(id,title,discount_type,discount_value,promotional_price_amount,ends_at),provider_profiles(business_name,city,average_rating,review_count)").eq("id", id).eq("status","published").eq("is_active", true).eq("service_options.is_active",true).eq("promotions.status","published").eq("promotions.is_active",true).lte("promotions.starts_at",now).gt("promotions.ends_at",now).maybeSingle(); return data as unknown as PublicService | null; }
export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> { const item = await loadService((await params).id); return item ? { title: item.title, description: item.description ?? `Réservez ${item.title} sur Mata Beauty.` } : { title: "Prestation introuvable" }; }
export default async function ServicePage({ params }: { params: Promise<{ id: string }> }) { const item = await loadService((await params).id); if (!item) notFound(); const promotion=item.promotions[0];const promoPrice=promotion?(promotion.promotional_price_amount??(promotion.discount_type==="percentage"?Math.round(item.price_amount*(1-promotion.discount_value/100)):Math.max(0,item.price_amount-promotion.discount_value))):null;return <main className="public-detail"><Link href="/discover">← Découvrir</Link><section>{item.cover_url&&<Image src={item.cover_url} alt={item.title} width={900} height={500} unoptimized/>}<small>{item.provider_profiles?.city ?? "Dakar"} · ★ {Number(item.provider_profiles?.average_rating??0).toFixed(1)} ({item.provider_profiles?.review_count??0} avis)</small><h1>{item.title}</h1><h2>{item.provider_profiles?.business_name ?? "Professionnel Mata Beauty"}</h2><p>{item.description ?? "Cette prestation est disponible à la réservation."}</p>{promotion&&<p><strong>{promotion.title}</strong> · valable jusqu’au {new Date(promotion.ends_at).toLocaleDateString("fr-FR")}</p>}<strong>{promoPrice!==null&&<del>{item.price_amount.toLocaleString("fr-FR")} FCFA · </del>}{(promoPrice??item.price_amount).toLocaleString("fr-FR")} FCFA · {item.duration_minutes} min</strong>{item.service_options.length>0&&<div><h2>Options & suppléments</h2>{item.service_options.map(option=><p key={option.id}>{option.name} · +{option.price_amount.toLocaleString("fr-FR")} FCFA{option.duration_minutes?` · +${option.duration_minutes} min`:""}{option.is_required?" · obligatoire":""}</p>)}</div>}<p>{item.location_modes.includes("client_address")?"Disponible en salon et à domicile":"Disponible en salon"}</p>{item.deposit_amount>0&&<p>Acompte prévu : {item.deposit_amount.toLocaleString("fr-FR")} FCFA</p>}{item.cancellation_policy&&<details><summary>Conditions d’annulation</summary><p>{item.cancellation_policy}</p>{item.client_instructions&&<p>{item.client_instructions}</p>}</details>}<Link className="public-primary" href={`/?service=${item.id}`}>Choisir un créneau</Link></section></main>; }
